/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CalledNumberInfo struct {
	// Called phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`
}
