/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CallQueueMemberInfo struct {
	// Link to a call queue member
	Uri string `json:"uri,omitempty"`
	// Internal identifier of a call queue member
	Id string `json:"id,omitempty"`
	// Extension number of a call queue member
	ExtensionNumber string `json:"extensionNumber,omitempty"`
}
