/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ExtensionCreationRequest struct {
	Contact ContactInfoCreationRequest `json:"contact"`
	// Number of extension
	ExtensionNumber string `json:"extensionNumber,omitempty"`
	// Password for extension. If not specified, the password is auto-generated
	Password string `json:"password,omitempty"`
	// List of non-RC internal identifiers assigned to an extension
	References       []ReferenceInfo  `json:"references,omitempty"`
	Roles            []Roles          `json:"roles,omitempty"`
	RegionalSettings RegionalSettings `json:"regionalSettings,omitempty"`
	// Specifies extension configuration wizard state (web service setup).
	SetupWizardState string `json:"setupWizardState,omitempty"`
	// Extension current state
	Status     string              `json:"status,omitempty"`
	StatusInfo ExtensionStatusInfo `json:"statusInfo,omitempty"`
	// Extension type
	Type string `json:"type"`
	// Hides extension from showing in company directory. Supported for extensions of User type only. For unassigned extensions the value is set to 'True' by default. For assigned extensions the value is set to 'False' by default
	Hidden bool `json:"hidden,omitempty"`
}
