/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ContactBusinessAddressInfo struct {
	// Country name of an extension user company
	Country string `json:"country,omitempty"`
	// State/province name of an extension user company. Mandatory for the USA, UK and Canada
	State string `json:"state,omitempty"`
	// City name of an extension user company
	City string `json:"city,omitempty"`
	// Street address of an extension user company
	Street string `json:"street,omitempty"`
	// Zip code of an extension user company
	Zip string `json:"zip,omitempty"`
}
