/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GetExtensionPhoneNumbersResponse struct {
	// List of phone numbers
	Records    []UserPhoneNumberInfo      `json:"records"`
	Navigation ProvisioningNavigationInfo `json:"navigation"`
	Paging     ProvisioningPagingInfo     `json:"paging"`
}
