/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ExtensionRegionalSettingRequest struct {
	HomeCountry      ExtensionCountryInfoRequest          `json:"homeCountry,omitempty"`
	Timezone         ExtensionTimezoneInfoRequest         `json:"timezone,omitempty"`
	Language         ExtensionLanguageInfoRequest         `json:"language,omitempty"`
	GreetingLanguage ExtensionGreetingLanguageInfoRequest `json:"greetingLanguage,omitempty"`
	FormattingLocale ExtensionFormattingLocaleInfoRequest `json:"formattingLocale,omitempty"`
	// Time format setting
	TimeFormat string `json:"timeFormat,omitempty"`
}
