/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type OrderBy struct {
	// Sorting priority index, starting from '1'. Optional if only one element in `orderBy` array is specified
	Index int32 `json:"index,omitempty"`
	// Field name by which to sort the contacts
	FieldName string `json:"fieldName,omitempty"`
	// Sorting direction
	Direction string `json:"direction,omitempty"`
}
