/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type DepartmentInfo struct {
	// Internal identifier of a department extension
	Id string `json:"id,omitempty"`
	// Canonical URI of a department extension
	Uri string `json:"uri,omitempty"`
	// Number of a department extension
	ExtensionNumber string `json:"extensionNumber,omitempty"`
}
