/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PhoneLineResource struct {
	LineType         string                   `json:"lineType,omitempty"`
	PhoneInfo        PhoneNumberResourceIntId `json:"phoneInfo,omitempty"`
	EmergencyAddress EmergencyAddress         `json:"emergencyAddress,omitempty"`
}
