/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type InstantMessageEventBody struct {
	// Internal identifier of a message
	Id string `json:"id,omitempty"`
	// Message receiver(s) information
	To   []NotificationRecipientInfo `json:"to,omitempty"`
	From SenderInfo                  `json:"from,omitempty"`
	// Type of a message. The default value is 'SMS'
	Type string `json:"type,omitempty"`
	// Message creation datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	CreationTime time.Time `json:"creationTime,omitempty"`
	// Datetime when the message was modified in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	LastModifiedTime time.Time `json:"lastModifiedTime,omitempty"`
	// Status of a message
	ReadStatus string `json:"readStatus,omitempty"`
	Priority   string `json:"priority,omitempty"`
	// Message attachment data
	Attachments []MessageAttachmentInfo `json:"attachments,omitempty"`
	// Message direction
	Direction string `json:"direction,omitempty"`
	// Message availability status
	Availability string `json:"availability,omitempty"`
	// Message subject. It replicates message text which is also returned as an attachment
	Subject string `json:"subject,omitempty"`
	// Status of a message
	MessageStatus string `json:"messageStatus,omitempty"`
	// Deprecated. Identifier of a conversation the message belongs to
	ConversationId string           `json:"conversationId,omitempty"`
	Conversation   ConversationInfo `json:"conversation,omitempty"`
	// Internal identifier of a subscription owner extension
	OwnerId string `json:"ownerId,omitempty"`
}
