/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CallersInfoRequest struct {
	// Phone number of a caller
	CallerId string `json:"callerId,omitempty"`
	// Contact name of a caller
	Name string `json:"name,omitempty"`
}
