/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CreateSipRegistrationRequest struct {
	// Device unique description
	Device []DeviceInfoRequest `json:"device"`
	// SIP settings for device
	SipInfo []SipInfoRequest `json:"sipInfo"`
}
