/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GlipMessageAttachmentAuthorInfo struct {
	// Name of a message author
	Name string `json:"name,omitempty"`
	// Link to an author's name
	Uri string `json:"uri,omitempty"`
	// Link to an image displayed to the left of an author's name; sized 82x82px
	IconUri string `json:"iconUri,omitempty"`
}
