/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PhoneLinesInfo struct {
	// Type of phone line
	LineType  string               `json:"lineType,omitempty"`
	PhoneInfo PhoneNumberInfoIntId `json:"phoneInfo,omitempty"`
}
