/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CallRecordingExtensions struct {
	// Link to call recording extension list resource
	Uri        string                       `json:"uri,omitempty"`
	Records    []CallRecordingExtensionInfo `json:"records,omitempty"`
	Navigation CallHandlingNavigationInfo   `json:"navigation,omitempty"`
	Paging     CallHandlingPagingInfo       `json:"paging,omitempty"`
}
