/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type TemplateInfo struct {
	// Link to a template
	Uri string `json:"uri,omitempty"`
	// Internal identifier of a template
	Id   string `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
	// Name of a template
	Name string `json:"name,omitempty"`
	// Time of a template creation
	CreationTime string `json:"creationTime,omitempty"`
	// Time of the last template modification
	LastModifiedTime string `json:"lastModifiedTime,omitempty"`
}
