/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type GlipMessageAttachmentFootnoteInfo struct {
	// Text of a footer
	Text string `json:"text,omitempty"`
	// Link to an icon displayed to the left of a footer; sized 32x32px
	IconUri string `json:"iconUri,omitempty"`
	// Message creation datetime in ISO 8601 format including timezone, for example *2016-03-10T18:07:52.534Z*
	Time time.Time `json:"time,omitempty"`
}
