/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CreateSipRegistrationResponse struct {
	// Suggested interval in seconds to periodically call SIP-provision API and update the local cache
	PollingInterval int32    `json:"pollingInterval,omitempty"`
	SipErrorCodes   []string `json:"sipErrorCodes,omitempty"`
	// SIP settings for device
	SipInfo []SipInfoResponse `json:"sipInfo"`
	// SIP flags data
	SipFlags []SipFlagsResponse `json:"sipFlags"`
}
