/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GlipConversationsList struct {
	// List of conversations
	Records    []GlipConversationInfo `json:"records"`
	Navigation GlipNavigationInfo     `json:"navigation,omitempty"`
}
