/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type NotificationDeliveryModeRequest struct {
	// Notifications transportation provider name. 'APNS' (Apple Push Notifications Service)
	TransportType string `json:"transportType,omitempty"`
	// Mandatory for 'APNS' and 'WebHook' transport types. For 'APNS' - internal identifier of a device 'device_token' for 'WebHook' - URL of a consumer service (cannot be changed during subscription update)
	Address string `json:"address,omitempty"`
	// Optional parameter. Specifies if the message will be encrypted or not. If request contains any presence event filter the value by default is 'True' (even if specified as 'false'). If request contains only message event filters the value by default is 'False'
	Encryption bool `json:"encryption,omitempty"`
	// For 'PubNub/APNS', 'APNS' and 'PubNub/GCM' transport types. Name of a certificate
	CertificateName string `json:"certificateName,omitempty"`
	// For 'PubNub/APNS' and 'PubNub/GCM' transport types. Identifier of a registration
	RegistrationId string `json:"registrationId,omitempty"`
	// For 'Webhook' transport type. Subscription verification key ensuring data security
	VerificationToken string `json:"verificationToken,omitempty"`
}
