/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PartyUpdateInfo struct {
	// True if the party is muted. False - otherwise
	Muted bool `json:"muted,omitempty"`
	// True if party is not connected to a session voice conference. False - otherwise
	StandAlone bool `json:"standAlone,omitempty"`
}
