/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type SyncInfoCallLog struct {
	// Type of synchronization
	SyncType string `json:"syncType,omitempty"`
	// Synchronization token
	SyncToken string `json:"syncToken,omitempty"`
	// The last synchronization datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	SyncTime time.Time `json:"syncTime,omitempty"`
}
