/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type RecordingInfo struct {
	// Internal identifier of a Recording resource
	Id string `json:"id,omitempty"`
	// True if the recording is active. False if the recording is paused.
	Active bool `json:"active,omitempty"`
}
