/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GetMessageList struct {
	// List of records with message information
	Records    []GetMessageInfoResponse `json:"records"`
	Navigation MessagingNavigationInfo  `json:"navigation"`
	Paging     MessagingPagingInfo      `json:"paging"`
}
