/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CallQueueExtensionInfo struct {
	// Target percentage of calls that must be answered by agents within the service level time threshold
	SlaGoal int32 `json:"slaGoal,omitempty"`
	// Period of time in seconds that is considered to be an acceptable service level
	SlaThresholdSeconds int32 `json:"slaThresholdSeconds,omitempty"`
	// If 'True' abandoned calls (hanged up prior to being served) are included into service level calculation
	IncludeAbandonedCalls bool `json:"includeAbandonedCalls,omitempty"`
	// Period of time in seconds specifying abandoned calls duration - calls that are shorter will not be included into the calculation of service level.; zero value means that abandoned calls of any duration will be included into calculation
	AbandonedThresholdSeconds int32 `json:"abandonedThresholdSeconds,omitempty"`
}
