/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GreetingInfo struct {
	// Type of a greeting, specifying the case when the greeting is played.
	Type string `json:"type,omitempty"`
	// Usage type of a greeting, specifying if the greeting is applied to user extension or department extension.
	UsageType string     `json:"usageType,omitempty"`
	Preset    PresetInfo `json:"preset,omitempty"`
}
