/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type UpdateGlipEveryoneRequest struct {
	// Everyone chat name. Maximum number of characters supported is 250
	Name int32 `json:"name,omitempty"`
	// Everyone chat description. Maximum number of characters supported is 1000
	Description string `json:"description,omitempty"`
}
