/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ModifyAccountBusinessAddressRequest struct {
	// Company business name
	Company string `json:"company,omitempty"`
	// Company business email address
	Email           string              `json:"email,omitempty"`
	BusinessAddress BusinessAddressInfo `json:"businessAddress"`
}
