/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type AuthenticationScheme struct {
	Description      string `json:"description,omitempty"`
	DocumentationUri string `json:"documentationUri,omitempty"`
	Name             string `json:"name,omitempty"`
	SpecUri          string `json:"specUri,omitempty"`
	Primary          bool   `json:"primary,omitempty"`
}
