/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type BlockedCallerGreetingInfo struct {
	// Type of a greeting
	Type   string     `json:"type,omitempty"`
	Preset PresetInfo `json:"preset,omitempty"`
}
