/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CustomCompanyGreetingLanguageInfo struct {
	// Internal identifier of a greeting language
	Id string `json:"id,omitempty"`
	// Link to a greeting language
	Uri string `json:"uri,omitempty"`
	// Name of a greeting language
	Name string `json:"name,omitempty"`
	// Locale code of a greeting language
	LocaleCode string `json:"localeCode,omitempty"`
}
