/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type EmergencyAddress struct {
	//  'True' if specifying of emergency address is required
	Required bool `json:"required,omitempty"`
	//  'True' if only local emergency address can be specified
	LocalOnly bool `json:"localOnly,omitempty"`
}
