/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type GlipConversationInfo struct {
	// Internal identifier of a conversation
	Id string `json:"id,omitempty"`
	// Type of a conversation
	Type string `json:"type,omitempty"`
	// Conversation creation datetime in ISO 8601 format
	CreationTime time.Time `json:"creationTime,omitempty"`
	// Conversation last change datetime in ISO 8601 format
	LastModifiedTime time.Time            `json:"lastModifiedTime,omitempty"`
	Members          []GlipChatMemberInfo `json:"members,omitempty"`
}
