/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type AccountDeviceUpdate struct {
	EmergencyServiceAddress EmergencyAddressInfoRequest `json:"emergencyServiceAddress,omitempty"`
	Extension               DeviceUpdateExtensionInfo   `json:"extension,omitempty"`
	PhoneLines              DeviceUpdatePhoneLinesInfo  `json:"phoneLines,omitempty"`
	// Supported only for devices assigned to Limited extensions. If true, enables users to log in to this phone as a common phone.
	UseAsCommonPhone bool `json:"useAsCommonPhone,omitempty"`
}
