/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type RecipientInfo struct {
	// Link to a recipient extension resource
	Uri string `json:"uri,omitempty"`
	// Internal identifier of a recipient extension
	Id string `json:"id,omitempty"`
}
