/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type HostInfoRequest struct {
	// Internal identifier of an extension which is assigned to be a meeting host. The default value is currently logged-in extension identifier
	Id string `json:"id,omitempty"`
}
