/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ContactList struct {
	// List of personal contacts from the extension address book
	Records    []PersonalContactResource  `json:"records,omitempty"`
	Navigation UserContactsNavigationInfo `json:"navigation,omitempty"`
	Paging     UserContactsPagingInfo     `json:"paging,omitempty"`
}
