/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PhoneNumberResourceIntId struct {
	// Internal identifier of a phone number
	Id        int64                    `json:"id,omitempty"`
	Country   CountryResource          `json:"country,omitempty"`
	Extension PhoneNumberExtensionInfo `json:"extension,omitempty"`
	// Custom user name of a phone number, if any
	Label string `json:"label,omitempty"`
	// Location (City, State). Filled for local US numbers
	Location string `json:"location,omitempty"`
	// Payment type. 'External' is returned for forwarded numbers which are not terminated in the RingCentral phone system = ['External', 'TollFree', 'Local'],
	PaymentType string `json:"paymentType,omitempty"`
	// Phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// Status of a phone number. If the value is 'Normal', the phone number is ready to be used. Otherwise it is an external number not yet ported to RingCentral ,
	Status    string `json:"status,omitempty"`
	UsageType string `json:"usageType,omitempty"`
	// Type of a phone number
	Type string `json:"type,omitempty"`
	// Internal identifier of a phone number reservation; encoded data including reservation type (by brand, by account, by session), particular brand/account/session data, and reservation date and time
	ReservationId string `json:"reservationId,omitempty"`
}
