/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PresenceInfoResource struct {
	UserStatus          string           `json:"userStatus,omitempty"`
	DndStatus           string           `json:"dndStatus,omitempty"`
	Message             string           `json:"message,omitempty"`
	AllowSeeMyPresence  bool             `json:"allowSeeMyPresence,omitempty"`
	RingOnMonitoredCall bool             `json:"ringOnMonitoredCall,omitempty"`
	PickUpCallsOnHold   bool             `json:"pickUpCallsOnHold,omitempty"`
	ActiveCalls         []ActiveCallInfo `json:"activeCalls,omitempty"`
}
