/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type DeviceInfoRequest struct {
	// Device unique identifier, retrieved on previous session (if any)
	Id string `json:"id,omitempty"`
	// For iOS devices only Certificate name (used by iOS applications for APNS subscription)
	AppExternalId string `json:"appExternalId,omitempty"`
	// For SoftPhone only Computer name
	ComputerName string `json:"computerName,omitempty"`
}
