/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ScimErrorResponse struct {
	// detail error message
	Detail  string   `json:"detail,omitempty"`
	Schemas []string `json:"schemas,omitempty"`
	// bad request type when status code is 400
	ScimType string `json:"scimType,omitempty"`
	// same as HTTP status code, e.g. 400, 401, etc.
	Status string `json:"status,omitempty"`
}
