/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type AccountResource struct {
	CompanyName   string              `json:"companyName,omitempty"`
	FederatedName string              `json:"federatedName,omitempty"`
	Id            string              `json:"id,omitempty"`
	MainNumber    PhoneNumberResource `json:"mainNumber,omitempty"`
}
