/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CallMonitoringGroupMemberList struct {
	// Link to a call monitoring group members resource
	Uri string `json:"uri"`
	// List of a call monitoring group members
	Records    []CallMonitoringGroupMemberInfo `json:"records"`
	Navigation ProvisioningNavigationInfo      `json:"navigation"`
	Paging     ProvisioningPagingInfo          `json:"paging"`
}
