/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type MessageEventBody struct {
	// Internal identifier of an extension
	ExtensionId string `json:"extensionId,omitempty"`
	// Datetime when the message was last modified in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	LastUpdated time.Time `json:"lastUpdated,omitempty"`
	// Message Changes
	Changes []MessageChanges `json:"changes,omitempty"`
	// Internal identifier of a subscription owner extension
	OwnerId string `json:"ownerId,omitempty"`
}
