/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GetCountryInfoState struct {
	// Internal identifier of a state
	Id string `json:"id,omitempty"`
	// Canonical URI of a state
	Uri string `json:"uri,omitempty"`
}
