/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type MessageChanges struct {
	// Message type
	Type string `json:"type,omitempty"`
	// The number of new messages. Can be omitted if the value is zero
	NewCount int32 `json:"newCount,omitempty"`
	// The number of updated messages. Can be omitted if the value is zero
	UpdatedCount int32 `json:"updatedCount,omitempty"`
}
