/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GetMessageInfoMultiResponse struct {
	// Internal identifier of a resource
	ResourceId string `json:"resourceId,omitempty"`
	// Status code of resource retrieval
	Status int32       `json:"status,omitempty"`
	Body   MessageBody `json:"body,omitempty"`
}
