/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

// Extension permissions, corresponding to the Service Web permissions 'Admin' and 'InternationalCalling'
type ExtensionPermissions struct {
	Admin                PermissionInfo `json:"admin,omitempty"`
	InternationalCalling PermissionInfo `json:"internationalCalling,omitempty"`
}
