/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GlipPreferencesChats struct {
	MaxCount     int32  `json:"maxCount,omitempty"`
	LeftRailMode string `json:"leftRailMode,omitempty"`
}
