/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ActiveCallInfo struct {
	Id        string `json:"id,omitempty"`
	Direction string `json:"direction,omitempty"`
	// Phone number or extension number of a caller. For GCM transport type '_from' property should be used
	From string `json:"from,omitempty"`
	// Name of a caller
	FromName string `json:"fromName,omitempty"`
	// Phone number or extension number of a callee
	To string `json:"to,omitempty"`
	// Name of a callee
	ToName string `json:"toName,omitempty"`
	// Time when the call is actually started
	StartTime       string           `json:"startTime,omitempty"`
	TelephonyStatus string           `json:"telephonyStatus,omitempty"`
	SipData         DetailedCallInfo `json:"sipData,omitempty"`
	SessionId       string           `json:"sessionId,omitempty"`
	TerminationType string           `json:"terminationType,omitempty"`
}
