/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ForwardingNumberResource struct {
	Uri         string   `json:"uri,omitempty"`
	Id          string   `json:"id,omitempty"`
	PhoneNumber string   `json:"phoneNumber,omitempty"`
	Label       string   `json:"label,omitempty"`
	Features    []string `json:"features,omitempty"`
	FlipNumber  string   `json:"flipNumber,omitempty"`
	// Forwarding phone number type
	Type string `json:"type,omitempty"`
}
