/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type UserAnsweringRuleListRecord struct {
	// Canonical URI to an answering rule resource
	Uri string `json:"uri,omitempty"`
	// Internal identifier of an asnwering rule
	Id string `json:"id,omitempty"`
	// Type of an answering rule
	Type string `json:"type,omitempty"`
	// Name of an answering rule specified by user
	Name string `json:"name,omitempty"`
	// Specifies if an answering rule is active or inactive
	Enabled bool `json:"enabled,omitempty"`
}
