/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ReferenceInfo struct {
	// Non-RC identifier of an extension
	Ref string `json:"ref,omitempty"`
	// Type of external identifier
	Type string `json:"type,omitempty"`
}
