/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type UpdateConferencingInfoRequest struct {
	// Multiple dial-in phone numbers to connect to audio conference service, relevant for user's brand. Each number is given with the country and location information, in order to let the user choose the less expensive way to connect to a conference. The first number in the list is the primary conference number, that is default and domestic
	PhoneNumbers []ConferencePhoneNumberInfo `json:"phoneNumbers,omitempty"`
	// Determines if host user allows conference participants to join before the host
	AllowJoinBeforeHost bool `json:"allowJoinBeforeHost,omitempty"`
}
