/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PatchOperation struct {
	Op   string `json:"op"`
	Path string `json:"path,omitempty"`
	// corresponding 'value' of that field specified by 'path'
	Value string `json:"value,omitempty"`
}
