/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PhoneNumberResource struct {
	FormattedPhoneNumber string `json:"formattedPhoneNumber,omitempty"`
	PhoneNumber          string `json:"phoneNumber,omitempty"`
	Type                 string `json:"type,omitempty"`
	// Custom user name of a phone number, if any
	Label string `json:"label,omitempty"`
	// Usage type of a phone number
	UsageType string `json:"usageType,omitempty"`
}
