/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GetExtensionDevicesResponse struct {
	// List of extension devices
	Records    []GetDeviceInfoResponse          `json:"records"`
	Navigation DeviceProvisioningNavigationInfo `json:"navigation"`
	Paging     DeviceProvisioningPagingInfo     `json:"paging"`
}
