/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type MeetingServiceInfoResource struct {
	Uri                  string                          `json:"uri,omitempty"`
	SupportUri           string                          `json:"supportUri,omitempty"`
	IntlDialInNumbersUri string                          `json:"intlDialInNumbersUri,omitempty"`
	ExternalUserInfo     MeetingExternalUserInfoResource `json:"externalUserInfo,omitempty"`
	DialInNumbers        []DialInNumberResource          `json:"dialInNumbers,omitempty"`
}
