/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GetRingOutStatusResponse struct {
	// Internal identifier of a RingOut call
	Id     string            `json:"id,omitempty"`
	Uri    string            `json:"uri,omitempty"`
	Status RingOutStatusInfo `json:"status,omitempty"`
}
