/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

// Updates either blocked or allowed phone number list with a new phone number.
type AddBlockedAllowedPhoneNumber struct {
	// A blocked/allowed phone number in [E.164](https://www.itu.int/rec/T-REC-E.164-201011-I) format
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// Custom name of a blocked/allowed phone number
	Label string `json:"label,omitempty"`
	// Status of a phone number
	Status string `json:"status,omitempty"`
}
