/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type UpdateAnsweringRuleRequest struct {
	Forwarding ForwardingInfoCreateRuleRequest `json:"forwarding,omitempty"`
	// Specifies if the rule is active or inactive. The default value is 'True'
	Enabled bool `json:"enabled,omitempty"`
	// Name of an answering rule specified by user
	Name string `json:"name,omitempty"`
	// Answering rule will be applied when calls are received from the specified caller(s)
	Callers []CallersInfoRequest `json:"callers,omitempty"`
	// Answering rules are applied when calling to selected number(s)
	CalledNumbers []CalledNumberInfo `json:"calledNumbers,omitempty"`
	Schedule      ScheduleInfo       `json:"schedule,omitempty"`
	// Specifies how incoming calls are forwarded
	CallHandlingAction      string                      `json:"callHandlingAction,omitempty"`
	UnconditionalForwarding UnconditionalForwardingInfo `json:"unconditionalForwarding,omitempty"`
	Queue                   QueueInfo                   `json:"queue,omitempty"`
	Voicemail               VoicemailInfo               `json:"voicemail,omitempty"`
	// Greetings applied for an answering rule; only predefined greetings can be applied, see Dictionary Greeting List
	Greetings []GreetingInfo `json:"greetings,omitempty"`
	// Call screening status. 'Off' - no call screening; 'NoCallerId' - if caller ID is missing, then callers are asked to say their name before connecting; 'UnknownCallerId' - if caller ID is not in contact list, then callers are asked to say their name before connecting; 'Always' - the callers are always asked to say their name before connecting. The default value is 'Off'
	Screening string `json:"screening,omitempty"`
	// Indicates whether inactive numbers should be returned or not.
	ShowInactiveNumbers bool `json:"showInactiveNumbers,omitempty"`
}
