/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ActiveCallInfoWithoutSip struct {
	// Internal identifier of a call
	Id string `json:"id,omitempty"`
	// Call direction
	Direction string `json:"direction,omitempty"`
	// Phone number or extension number of a caller. For GCM transport type '_from' property should be used
	From string `json:"from,omitempty"`
	// Name of a caller
	FromName string `json:"fromName,omitempty"`
	// Phone number or extension number of a callee
	To string `json:"to,omitempty"`
	// Name of a callee
	ToName string `json:"toName,omitempty"`
	// Time when the call is actually started
	StartTime string `json:"startTime,omitempty"`
	// Telephony call status
	TelephonyStatus string `json:"telephonyStatus,omitempty"`
	// Internal identifier of a call session
	SessionId string `json:"sessionId,omitempty"`
	// Type of call termination. Supported for calls in 'NoCall' status. If the returned termination type is 'intermediate' it means the call is not actually ended, the connection is established on one of the devices
	TerminationType string `json:"terminationType,omitempty"`
}
