/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type AudioPromptInfo struct {
	// Link to an prompt audio file
	Uri string `json:"uri,omitempty"`
	// Internal identifier of an prompt
	Id string `json:"id,omitempty"`
}
