/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type RegionalSettings struct {
	HomeCountry      CountryInfo          `json:"homeCountry,omitempty"`
	Timezone         TimezoneInfo         `json:"timezone,omitempty"`
	Language         LanguageInfo         `json:"language,omitempty"`
	GreetingLanguage GreetingLanguageInfo `json:"greetingLanguage,omitempty"`
	FormattingLocale FormattingLocaleInfo `json:"formattingLocale,omitempty"`
	// Time format setting. The default value is '12h' = ['12h', '24h']
	TimeFormat string `json:"timeFormat,omitempty"`
}
