/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type CompanyCallLogRecord struct {
	// Internal identifier of a cal log record
	Id string `json:"id,omitempty"`
	// Canonical URI of a call log record
	Uri string `json:"uri,omitempty"`
	// Internal identifier of a call session
	SessionId string            `json:"sessionId,omitempty"`
	From      CallLogCallerInfo `json:"from,omitempty"`
	To        CallLogCallerInfo `json:"to,omitempty"`
	// Call type
	Type string `json:"type,omitempty"`
	// Call direction
	Direction string `json:"direction,omitempty"`
	// Indicates whether the record is deleted. Returned for deleted records, for ISync requests
	Deleted bool `json:"deleted,omitempty"`
	// Action description of the call operation
	Action string `json:"action,omitempty"`
	// Status description of the call operation
	Result string `json:"result,omitempty"`
	// The call start datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	StartTime time.Time `json:"startTime,omitempty"`
	// Call duration in seconds
	Duration  int32                `json:"duration,omitempty"`
	Recording CallLogRecordingInfo `json:"recording,omitempty"`
}
