/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GetPresenceExtensionInfo struct {
	// Internal identifier of an extension
	Id string `json:"id,omitempty"`
	// Canonical URI of an extension
	Uri string `json:"uri,omitempty"`
	// Extension number (usually 3 or 4 digits)
	ExtensionNumber string `json:"extensionNumber,omitempty"`
}
