/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GlipTeamsList struct {
	// List of teams
	Records    []GlipTeamInfo     `json:"records"`
	Navigation GlipNavigationInfo `json:"navigation,omitempty"`
}
