/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CallerIdDeviceInfo struct {
	// Internal identifier of a device
	Id string `json:"id,omitempty"`
	// Link to a device resource
	Uri string `json:"uri,omitempty"`
	// Name of a device
	PhoneNumber string `json:"phoneNumber,omitempty"`
}
