/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

// Format of response in case that any error occured during request processing
type ErrorResponse struct {
	// Collection of all gathered errors
	Errors []Error `json:"errors,omitempty"`
}
