/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CompanyAnsweringRuleScheduleInfoRequest struct {
	WeeklyRanges CompanyAnsweringRuleWeeklyScheduleInfoRequest `json:"weeklyRanges,omitempty"`
	// Specific data ranges. If specified, weeklyRanges cannot be specified
	Ranges []RangesInfo `json:"ranges,omitempty"`
	// Reference to Business Hours or After Hours schedule
	Ref string `json:"ref,omitempty"`
}
