/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CallRecordingExtensionResource struct {
	// Internal identifier of an extension
	Id              string `json:"id,omitempty"`
	Uri             string `json:"uri,omitempty"`
	ExtensionNumber string `json:"extensionNumber,omitempty"`
	Type            string `json:"type,omitempty"`
	// Direction of call
	CallDirection string `json:"callDirection,omitempty"`
}
