/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ExtensionUpdateRequest struct {
	Status     string              `json:"status,omitempty"`
	StatusInfo ExtensionStatusInfo `json:"statusInfo,omitempty"`
	// Type of suspension
	Reason string `json:"reason,omitempty"`
	// Free Form user comment
	Comment string `json:"comment,omitempty"`
	// Extension number available
	ExtensionNumber  string                          `json:"extensionNumber,omitempty"`
	Contact          ContactInfoUpdateRequest        `json:"contact,omitempty"`
	RegionalSettings ExtensionRegionalSettingRequest `json:"regionalSettings,omitempty"`
	SetupWizardState string                          `json:"setupWizardState,omitempty"`
	//  Extension partner identifier
	PartnerId string `json:"partnerId,omitempty"`
	// IVR PIN
	IvrPin string `json:"ivrPin,omitempty"`
	// Password for extension
	Password      string               `json:"password,omitempty"`
	CallQueueInfo CallQueueInfoRequest `json:"callQueueInfo,omitempty"`
	Transition    []UserTransitionInfo `json:"transition,omitempty"`
}
