/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PhoneNumberInfoNumberParser struct {
	// Area code of location. The portion of the [E.164](https://www.itu.int/rec/T-REC-E.164-201011-I) number that identifies a specific geographic region/numbering area of the national numbering plan (NANP); that can be summarized as `NPA-NXX-xxxx` and covers Canada, the United States, parts of the Caribbean Sea, and some Atlantic and Pacific islands. See [North American Numbering Plan] (https://en.wikipedia.org/wiki/North_American_Numbering_Plan) for details
	AreaCode string `json:"areaCode,omitempty"`
	// Information on a country the phone number belongs to
	Country []GetCountryInfoNumberParser `json:"country,omitempty"`
	// Dialing format of a phone number
	Dialable string `json:"dialable,omitempty"`
	// Phone number [E.164](https://www.itu.int/rec/T-REC-E.164-201011-I) format
	E164 string `json:"e164,omitempty"`
	// International format of a phone number
	FormattedInternational string `json:"formattedInternational,omitempty"`
	// Domestic format of a phone number
	FormattedNational string `json:"formattedNational,omitempty"`
	// One of the numbers to be parsed, passed as a string in response
	OriginalString string `json:"originalString,omitempty"`
	// 'True' if the number is in a special format (for example N11 code)
	Special bool `json:"special,omitempty"`
	// Phone number [E.164](https://www.itu.int/rec/T-REC-E.164-201011-I) format without plus sign ('+')
	Normalized string `json:"normalized,omitempty"`
	// Specifies if a phone number is toll free or not
	TollFree bool `json:"tollFree,omitempty"`
	// Sub-Address. The portion of the number that identifies a subscriber into the subscriber internal (non-public) network.
	SubAddress string `json:"subAddress,omitempty"`
	//  Subscriber number. The portion of the [E.164](https://www.itu.int/rec/T-REC-E.164-201011-I) number that identifies a subscriber in a network or numbering area.
	SubscriberNumber string `json:"subscriberNumber,omitempty"`
	// DTMF (Dual Tone Multi-Frequency) postfix
	DtmfPostfix string `json:"dtmfPostfix,omitempty"`
}
