/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ServicePlanInfo struct {
	// Internal identifier of a service plan
	Id string `json:"id,omitempty"`
	// Name of a service plan
	Name string `json:"name,omitempty"`
	// Edition of a service plan
	Edition string `json:"edition,omitempty"`
}
