/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ExtensionPermissionsResource struct {
	Uri                      string     `json:"uri,omitempty"`
	Admin                    Permission `json:"admin,omitempty"`
	InternationalCalling     Permission `json:"internationalCalling,omitempty"`
	FreeSoftPhoneDigitalLine Permission `json:"freeSoftPhoneDigitalLine,omitempty"`
}
