/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type MessageStoreReport struct {
	// Internal identifier of a message store report task
	Id string `json:"id,omitempty"`
	// Link to a task
	Uri string `json:"uri,omitempty"`
	// Status of a message store report task
	Status string `json:"status,omitempty"`
	// Internal identifier of an account
	AccountId string `json:"accountId,omitempty"`
	// Internal identifier of an extension
	ExtensionId string `json:"extensionId,omitempty"`
	// Task creation time
	CreationTime string `json:"creationTime,omitempty"`
	// Time of the last task modification
	LastModifiedTime string `json:"lastModifiedTime,omitempty"`
	// Ending time for collecting messages
	DateTo string `json:"dateTo,omitempty"`
	// Starting time for collecting messages
	DateFrom string `json:"dateFrom,omitempty"`
}
