/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GlipMessageAttachmentFieldsInfo struct {
	// Title of an individual field
	Title string `json:"title,omitempty"`
	// Value of an individual field (supports Markdown)
	Value string `json:"value,omitempty"`
	// Style of width span applied to a field
	Style string `json:"style,omitempty"`
}
