/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type MakeRingOutCallerInfoRequestFrom struct {
	// Phone number in E.164 format
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// Internal identifier of a forwarding number; returned in response as an 'id' field value. Can be specified instead of the phoneNumber attribute
	ForwardingNumberId string `json:"forwardingNumberId,omitempty"`
}
