/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type CompanyAnsweringRuleList struct {
	// Link to an answering rule resource
	Uri string `json:"uri,omitempty"`
	// List of company answering rules
	Records    []ListCompanyAnsweringRuleInfo `json:"records,omitempty"`
	Paging     CallHandlingPagingInfo         `json:"paging,omitempty"`
	Navigation CallHandlingNavigationInfo     `json:"navigation,omitempty"`
}
