/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

// Peer session / party data. Valid in Gone state only
type PeerInfo struct {
	SessionId string `json:"sessionId,omitempty"`
	PartyId   string `json:"partyId,omitempty"`
}
