/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

// Conversation is opened
type GlipPostMembersListBodyMembers struct {
	// Internal identifier of a person
	Id string `json:"id,omitempty"`
	// Email of a person
	Email string `json:"email,omitempty"`
}
