/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type UserAnsweringRuleListPaging struct {
	// The current page number. 1-indexed, so the first page is 1 by default. May be omitted if result is empty (because non-existent page was specified or perPage=0 was requested)
	Page int32 `json:"page,omitempty"`
	// The total number of pages in a dataset.
	TotalPages int32 `json:"totalPages,omitempty"`
	// Current page size, describes how many items are in each page. Default value is 100. Maximum value is 1000. If perPage value in the request is greater than 1000, the maximum value (1000) is applied
	PerPage int32 `json:"perPage,omitempty"`
	// The total number of elements in a dataset.
	TotalElements int32 `json:"totalElements,omitempty"`
	// The zero-based number of the first element on the current page. Omitted if the page is omitted or result is empty
	PageStart int32 `json:"pageStart,omitempty"`
	// The zero-based index of the last element on the current page. Omitted if the page is omitted or result is empty
	PageEnd int32 `json:"pageEnd,omitempty"`
}
