/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type IvrPrompts struct {
	// Link to prompts library resource
	Uri string `json:"uri,omitempty"`
	// List of Prompts
	Records    []PromptInfo               `json:"records,omitempty"`
	Navigation CallHandlingNavigationInfo `json:"navigation,omitempty"`
	Paging     CallHandlingPagingInfo     `json:"paging,omitempty"`
}
