/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type PersonalContactRequest struct {
	// First name of the contact
	FirstName string `json:"firstName,omitempty"`
	// Last name of the contact
	LastName string `json:"lastName,omitempty"`
	// Middle name of the contact
	MiddleName string `json:"middleName,omitempty"`
	// Nick name of the contact
	NickName string `json:"nickName,omitempty"`
	// Company name of the contact
	Company string `json:"company,omitempty"`
	// Job title of the contact
	JobTitle string `json:"jobTitle,omitempty"`
	// Email of the contact
	Email string `json:"email,omitempty"`
	// 2nd email of the contact
	Email2 string `json:"email2,omitempty"`
	// 3rd email of the contact
	Email3 string `json:"email3,omitempty"`
	// Date of birth of the contact
	Birthday time.Time `json:"birthday,omitempty"`
	// The contact home page URL
	WebPage string `json:"webPage,omitempty"`
	// Notes for the contact
	Notes string `json:"notes,omitempty"`
	// Home phone number of the contact in e.164 (with \"+\") format
	HomePhone string `json:"homePhone,omitempty"`
	// 2nd home phone number of the contact in e.164 (with \"+\") format
	HomePhone2 string `json:"homePhone2,omitempty"`
	// Business phone of the contact in e.164 (with \"+\") format
	BusinessPhone string `json:"businessPhone,omitempty"`
	// 2nd business phone of the contact in e.164 (with \"+\") format
	BusinessPhone2 string `json:"businessPhone2,omitempty"`
	// Mobile phone of the contact in e.164 (with \"+\") format
	MobilePhone string `json:"mobilePhone,omitempty"`
	// Business fax number of the contact in e.164 (with \"+\") format
	BusinessFax string `json:"businessFax,omitempty"`
	// Company number of the contact in e.164 (with \"+\") format
	CompanyPhone string `json:"companyPhone,omitempty"`
	// Phone number of the contact assistant in e.164 (with \"+\") format
	AssistantPhone string `json:"assistantPhone,omitempty"`
	// Car phone number of the contact in e.164 (with \"+\") format
	CarPhone string `json:"carPhone,omitempty"`
	// Other phone number of the contact in e.164 (with \"+\") format
	OtherPhone string `json:"otherPhone,omitempty"`
	// Other fax number of the contact in e.164 (with \"+\") format
	OtherFax string `json:"otherFax,omitempty"`
	// Callback phone number of the contact in e.164 (with \"+\") format
	CallbackPhone   string             `json:"callbackPhone,omitempty"`
	HomeAddress     ContactAddressInfo `json:"homeAddress,omitempty"`
	BusinessAddress ContactAddressInfo `json:"businessAddress,omitempty"`
	OtherAddress    ContactAddressInfo `json:"otherAddress,omitempty"`
}
