/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type DeviceProvisioningNavigationInfo struct {
	FirstPage    DeviceProvisioningNavigationInfoUri `json:"firstPage,omitempty"`
	NextPage     DeviceProvisioningNavigationInfoUri `json:"nextPage,omitempty"`
	PreviousPage DeviceProvisioningNavigationInfoUri `json:"previousPage,omitempty"`
	LastPage     DeviceProvisioningNavigationInfoUri `json:"lastPage,omitempty"`
}
