/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type User struct {
	// user status
	Active    bool          `json:"active,omitempty"`
	Addresses []UserAddress `json:"addresses,omitempty"`
	Emails    []Email       `json:"emails"`
	// external unique resource id defined by provisioning client
	ExternalId string `json:"externalId,omitempty"`
	// unique resource id defined by RingCentral
	Id                                                string         `json:"id,omitempty"`
	Name                                              Name           `json:"name"`
	PhoneNumbers                                      []PhoneNumber  `json:"phoneNumbers,omitempty"`
	Photos                                            []Photo        `json:"photos,omitempty"`
	Schemas                                           []string       `json:"schemas"`
	Urnietfparamsscimschemasextensionenterprise20User EnterpriseUser `json:"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User,omitempty"`
	// MUST be same as work type email address
	UserName string `json:"userName"`
}
