/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type IvrMenuPromptInfo struct {
	// Prompt mode: custom media or text
	Mode  string             `json:"mode,omitempty"`
	Audio PromptLanguageInfo `json:"audio,omitempty"`
	// For 'TextToSpeech' mode only. Prompt text
	Text     string          `json:"text,omitempty"`
	Language AudioPromptInfo `json:"language,omitempty"`
}
