/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type PagingOnlyGroupUsers struct {
	// List of users allowed to page this group
	Records    []PagingGroupExtensionInfo `json:"records,omitempty"`
	Navigation ProvisioningNavigationInfo `json:"navigation,omitempty"`
	Paging     ProvisioningPagingInfo     `json:"paging,omitempty"`
}
