/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type ForwardingNumberInfoRulesCreateRuleRequest struct {
	// Internal identifier of a forwarding number
	Id string `json:"id,omitempty"`
	// Forwarding phone number type
	Type string `json:"type,omitempty"`
}
