/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type UpdateMessageRequest struct {
	// Read status of a message to be changed. Multiple values are accepted
	ReadStatus string `json:"readStatus,omitempty"`
}
