/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GlipPostPostBodyAttachments struct {
	// Internal identifier of an attachment
	Id string `json:"id,omitempty"`
	// Attachment type
	Type string `json:"type,omitempty"`
}
