/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type AlertInfo struct {
	// Title of a message
	Title string `json:"title,omitempty"`
	// Message Description
	Body string `json:"body,omitempty"`
}
