/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

type FaxResponse struct {
	// Internal identifier of a message
	Id int64 `json:"id,omitempty"`
	// Canonical URI of a message
	Uri string `json:"uri,omitempty"`
	// Message type - 'Fax'
	Type string         `json:"type,omitempty"`
	From CallerInfoFrom `json:"from,omitempty"`
	// Recipient information
	To []CallerInfoTo `json:"to,omitempty"`
	// Message creation datetime in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	CreationTime time.Time `json:"creationTime,omitempty"`
	// Message read status
	ReadStatus string `json:"readStatus,omitempty"`
	// Message priority
	Priority string `json:"priority,omitempty"`
	// The list of message attachments
	Attachments []MessageAttachmentInfoIntId `json:"attachments,omitempty"`
	// Message direction
	Direction string `json:"direction,omitempty"`
	// Message availability status. Message in 'Deleted' state is still preserved with all its attachments and can be restored. 'Purged' means that all attachments are already deleted and the message itself is about to be physically deleted shortly
	Availability string `json:"availability,omitempty"`
	// Message status. 'Queued' - the message is queued for sending; 'Sent' - a message is successfully sent; 'SendingFailed' - a message sending attempt has failed; 'Received' - a message is received (inbound messages have this status by default)
	MessageStatus string `json:"messageStatus,omitempty"`
	// Resolution of a fax message. ('High' for black and white image scanned at 200 dpi, 'Low' for black and white image scanned at 100 dpi)
	FaxResolution string `json:"faxResolution,omitempty"`
	// Page count in a fax message
	FaxPageCount int32 `json:"faxPageCount,omitempty"`
	// Datetime when the message was modified on server in ISO 8601 format including timezone, for example 2016-03-10T18:07:52.534Z
	LastModifiedTime time.Time `json:"lastModifiedTime,omitempty"`
	// Cover page identifier. For the list of available cover page identifiers please call the Fax Cover Pages method
	CoverIndex int32 `json:"coverIndex,omitempty"`
	// Cover page text, entered by the fax sender and printed on the cover page. Maximum length is limited to 1024 symbols
	CoverPageText string `json:"coverPageText,omitempty"`
}
