/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

import (
	"time"
)

// Returned if WebHook subscription is blacklisted
type NotificationBlacklistedData struct {
	// Time of adding subscrition to a black list in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format including timezone, for example *2016-03-10T18:07:52.534Z*
	BlacklistedAt time.Time `json:"blacklistedAt,omitempty"`
	// Reason of adding subscrition to a black list
	Reason string `json:"reason,omitempty"`
}
