/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GlipMentionsInfo struct {
	// Internal identifier of a user
	Id string `json:"id,omitempty"`
	// Type of mentions
	Type string `json:"type,omitempty"`
	// Name of a user
	Name string `json:"name,omitempty"`
}
