/*
 * RingCentral Connect Platform API
 *
 * RingCentral Connect Platform API
 *
 * API version: 1.0.36
 * Contact: platform@ringcentral.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ringcentral

type GrantInfo struct {
	// Canonical URI of a grant
	Uri       string              `json:"uri,omitempty"`
	Extension ExtensionInfoGrants `json:"extension,omitempty"`
	// Specifies if picking up of other extensions' calls is allowed for the extension. If 'Presence' feature is disabled for the given extension, the flag is not returned
	CallPickup bool `json:"callPickup,omitempty"`
	// Specifies if monitoring of other extensions' calls is allowed for the extension. If 'CallMonitoring' feature is disabled for the given extension, the flag is not returned
	CallMonitoring bool `json:"callMonitoring,omitempty"`
	// Specifies whether the current extension is able to make or receive calls on behalf of the user referenced in extension object
	CallOnBehalfOf bool `json:"callOnBehalfOf,omitempty"`
	// Specifies whether the current extension can delegate a call to the user referenced in extension object
	CallDelegation bool `json:"callDelegation,omitempty"`
	// Specifies whether the current extension is allowed to call Paging Only group referenced to in extension object
	GroupPaging bool `json:"groupPaging,omitempty"`
}
